"""Load and run ollama models"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_llm.ipynb.

# %% auto 0
__all__ = ['list_local_models', 'create_message', 'OutputSchema', 'LLM']

# %% ../nbs/00_llm.ipynb 2
import dotenv


# %% ../nbs/00_llm.ipynb 3
dotenv.load_dotenv()


# %% ../nbs/00_llm.ipynb 4
from typing import Literal, Optional
from ollama import list as ollama_list


# %% ../nbs/00_llm.ipynb 6
def list_local_models():
  """List local models."""
  return [m.model for m in ollama_list()["models"]]


# %% ../nbs/00_llm.ipynb 8
from tqdm import tqdm
from ollama import pull


# %% ../nbs/00_llm.ipynb 9
def _download_model(model_name: str):
  """Download a model from ollama."""
  current_digest, bars = "", {}
  for progress in pull(model_name, stream=True):
    digest = progress.get("digest", "")
    if digest != current_digest and current_digest in bars:
      bars[current_digest].close()

    if not digest:
      print(progress.get("status"))
      continue

    if digest not in bars and (total := progress.get("total")):
      bars[digest] = tqdm(total=total, desc=f"pulling {digest[7:19]}", unit="B", unit_scale=True)

    if completed := progress.get("completed"):
      bars[digest].update(completed - bars[digest].n)

    current_digest = digest


# %% ../nbs/00_llm.ipynb 11
from ollama import chat as ollama_chat


# %% ../nbs/00_llm.ipynb 13
def create_message(content: Optional[str], role: Literal["user", "assistant", "system"] = "user"):
  """Create a message for the chat."""
  return {"role": role, "content": content}


# %% ../nbs/00_llm.ipynb 14
def _chat_one(model: str, message: str, think: Optional[bool] = None, **kwargs):
  """Chat with the model."""
  return ollama_chat(
    model=model, think=think, messages=[create_message(message)], **kwargs
  ).message.content


# %% ../nbs/00_llm.ipynb 16
from pydantic import BaseModel


# %% ../nbs/00_llm.ipynb 17
class OutputSchema(BaseModel):
  """Base class for structured LLM outputs. Subclass this to define your schema.

  The `content` field is required and will be used for chat history."""

  content: str


# %% ../nbs/00_llm.ipynb 21
from ollama import ChatResponse
from litellm import completion as litellm_completion


# %% ../nbs/00_llm.ipynb 26
class LLM:
  """A class for interacting with an LLM."""

  def __init__(
    self,
    model_name: str,  # The name of the model to use
    system_prompt: str = "",  # The system prompt to use.
    think: Optional[bool] = None,  # Whether to enable thinking mode
    output_schema: Optional[
      type[OutputSchema]
    ] = None,  # Schema for structured output (must subclass OutputSchema)
  ):
    self.model_name = model_name
    self.system_prompt = system_prompt
    self.output_schema = output_schema
    self.messages: list[dict] = [create_message(system_prompt, "system")]
    self.think = think
    self.use_openrouter = "openrouter" in model_name

    if not self.use_openrouter:
      self._verify()

  def generate(self, message: str, **kwargs) -> str | OutputSchema:
    """One-shot generation. Does not maintain conversation history."""
    messages = [create_message(self.system_prompt, "system"), create_message(message, "user")]
    if self.use_openrouter:
      return self._cloud_call(messages, **kwargs)
    return self._local_call(messages, **kwargs)

  def chat(self, message: str, **kwargs) -> str | OutputSchema:
    """Multi-turn chat. Maintains conversation history."""
    self.messages.append(create_message(message, "user"))

    if self.use_openrouter:
      response = self._cloud_call(self.messages, **kwargs)
    else:
      response = self._local_call(self.messages, **kwargs)

    # Extract content for history: schema responses have .content, plain responses are strings
    if isinstance(response, OutputSchema):
      self.messages.append(create_message(response.content, "assistant"))
    else:
      self.messages.append(create_message(response, "assistant"))
    return response

  def _local_call(self, messages: list[dict], **kwargs) -> str | OutputSchema:
    """Call local Ollama model."""
    response: ChatResponse = ollama_chat(
      model=self.model_name,
      think=self.think,
      messages=messages,
      format=self.output_schema.model_json_schema() if self.output_schema else None,
      **kwargs,
    )
    return self._parse_response(response.message.content)

  def _cloud_call(self, messages: list[dict], **kwargs) -> str | OutputSchema:
    """Call cloud model via litellm."""
    if self.think is True:
      kwargs["reasoning_effort"] = "low"
    response = litellm_completion(
      model=self.model_name,
      messages=messages,
      response_format=self.output_schema if self.output_schema else None,
      **kwargs,
    )
    return self._parse_response(response.choices[0].message.content)

  def _parse_response(self, content: Optional[str]) -> str | OutputSchema:
    """Parse raw response content, validating against schema if set."""
    assert content is not None, "No content was returned"
    if self.output_schema:
      return self.output_schema.model_validate_json(content)
    return content

  async def agenerate_batch(
    self,
    messages: list[str],
    concurrency: int = 10,
    show_progress: bool = True,
    **kwargs,
  ) -> list[str | OutputSchema]:
    """Batch async generation with concurrency control.

    Args:
        messages: List of input messages to process
        concurrency: Max parallel requests (default 10)
        show_progress: Show tqdm progress bar
        **kwargs: Additional args passed to the API (e.g., temperature)

    Returns:
        List of responses in same order as inputs
    """
    import asyncio
    from tqdm.asyncio import tqdm_asyncio

    semaphore = asyncio.Semaphore(concurrency)

    if self.use_openrouter:
      from litellm import acompletion

      async def process_one(message: str) -> str | OutputSchema:
        async with semaphore:
          msgs = [create_message(self.system_prompt, "system"), create_message(message, "user")]
          response = await acompletion(
            model=self.model_name,
            messages=msgs,
            response_format=self.output_schema if self.output_schema else None,
            **kwargs,
          )
          return self._parse_response(response.choices[0].message.content)
    else:
      from ollama import AsyncClient

      async def process_one(message: str) -> str | OutputSchema:
        async with semaphore:
          msgs = [create_message(self.system_prompt, "system"), create_message(message, "user")]
          client = AsyncClient()
          response = await client.chat(
            model=self.model_name,
            messages=msgs,
            format=self.output_schema.model_json_schema() if self.output_schema else None,
            **kwargs,
          )
          return self._parse_response(response.message.content)

    tasks = [process_one(msg) for msg in messages]
    if show_progress:
      return await tqdm_asyncio.gather(*tasks, desc="Processing")
    return await asyncio.gather(*tasks)

  def _verify(self):
    """Verify the model is available, download if missing."""
    if self.model_name not in list_local_models():
      _download_model(self.model_name)

